using Photon.Pun;
using Photon.Realtime;
using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections.Generic;
public class PunGameManager : MonoBehaviourPunCallbacks
{
    static public PunGameManager Instance;

    private GameObject instance;

    [Tooltip("The prefab to use for representing the player")]
    [SerializeField]
    private GameObject playerPrefab;

    [SerializeField] public Transform[] _spawnPoint;
    
    private List<GameObject> _tanks;
    private void Awake()
    {
        Instance = this;

        if (!PhotonNetwork.IsConnected)
        {
            SceneManager.LoadScene("Launcher");
            return;
        }

        if (TankMovement.LocalPlayerInstance == null)
        {
            Debug.LogFormat("We are Instantiating LocalPlayer from {0}", SceneManagerHelper.ActiveSceneName);

            Debug.LogError(PhotonNetwork.CurrentRoom.PlayerCount);
            // we're in a room. spawn a character for the local player. it gets synced by using PhotonNetwork.Instantiate
            // var tank = PhotonNetwork.Instantiate(this.playerPrefab.name, _spawnPoint[PhotonNetwork.CurrentRoom.PlayerCount - 1].position, _spawnPoint[PhotonNetwork.CurrentRoom.PlayerCount - 1].rotation, 0);
            var rand = Random.Range(0, _spawnPoint.Length);
            var tank = PhotonNetwork.Instantiate(this.playerPrefab.name, _spawnPoint[rand].position, _spawnPoint[rand].rotation, 0);
            //tank.GetComponent<MeshRenderer>().material.color = Color.green;  
        }
        else
        {

            Debug.LogFormat("Ignoring scene load for {0}", SceneManagerHelper.ActiveSceneName);
        }

    }


   
    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            QuitApplication();
        }
    }



    public override void OnPlayerEnteredRoom(Player other)
    {
        Debug.Log("OnPlayerEnteredRoom() " + other.NickName);

        if (PhotonNetwork.IsMasterClient)
        {
            Debug.LogFormat("OnPlayerEnteredRoom IsMasterClient {0}", PhotonNetwork.IsMasterClient);

            //playerPrefab.GetComponent<MeshRenderer>().material.color = Color.blue;
            //LoadArena();
        }
    }

    public override void OnPlayerLeftRoom(Player other)
    {
        Debug.Log("OnPlayerLeftRoom() " + other.NickName); // seen when other disconnects

        if (PhotonNetwork.IsMasterClient)
        {
            Debug.LogFormat("OnPlayerEnteredRoom IsMasterClient {0}", PhotonNetwork.IsMasterClient); // called before OnPlayerLeftRoom

            //LoadArena();
        }
    }

    public override void OnLeftRoom()
    {
        SceneManager.LoadScene("Launcher");
    }

    public bool LeaveRoom()
    {
        return PhotonNetwork.LeaveRoom();
    }

    public void QuitApplication()
    {
        Application.Quit();
    }

    //void LoadArena()
    //{
    //    if (!PhotonNetwork.IsMasterClient)
    //    {
    //        Debug.LogError("PhotonNetwork : Trying to Load a level but we are not the master Client");
    //    }

    //    Debug.LogFormat("PhotonNetwork : Loading Level : {0}", PhotonNetwork.CurrentRoom.PlayerCount);

    //    PhotonNetwork.LoadLevel("PunBasics-Room for " + PhotonNetwork.CurrentRoom.PlayerCount);
    //}
}
